server:
  port: 8085

spring:
  application:
    name: monitoring-agent

agent:
  tenant-id: ${AGENT_TENANT_ID}
  agent-id: ${AGENT_AGENT_ID}
  service-name: ${AGENT_SERVICE_NAME}
  service-instance-id: ${AGENT_SERVICE_INSTANCE_ID}
  environment: ${AGENT_ENVIRONMENT}

  health-url: ${AGENT_HEALTH_URL}

  backend-url: ${AGENT_BACKEND_URL}
  api-key: ${AGENT_API_KEY}

  health-interval-ms: ${AGENT_HEALTH_INTERVAL_MS:2000}

logging:
  level:
    root: INFO
    com.agent: DEBUG
